# Generated by Django 3.1.12 on 2025-01-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20250113_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagUrl',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
