# Generated by Django 3.1.12 on 2025-01-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_product_imagurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isFav',
            field=models.BooleanField(default=False),
        ),
    ]
